id: P6953A7F7
initial_creation_type: input
source_metadata:
  title: Śrī Siṃha
  language: en
  description: 'Texts by and about Śrī Siṃha (shrI sing+ha/shrI seng+ha), one of the
    early masters of the Dzogchen lineage:'
  volume:
    971f46ca1654406487a70685a708d144:
      title: Unravelling Mantra’s Meaning in The Heart of Wisdom Sūtra
      parent: Commentaries
created_at: '2022-03-01T02:24:55.026704'
last_modified_at: '2022-03-01T02:24:55.026710'
